function [] = updateTextPursuit(trial, fig, choice, name)

screenSize = get(0,'ScreenSize');
xPosition = 10; %screenSize(3)*2/3-50;
yPosition = screenSize(4)-screenSize(4)*2/3; %screenSize(4)*2/5-50;
verticalDistance = 20;
width = 180 ;
height = 20;
textblock = 0;

fileNameText = uicontrol(fig,'Style','text',...
    'String', ['Task: ' name],...
    'Position',[xPosition yPosition width height],...
    'HorizontalAlignment','left'); 

textblock = textblock+1;
fileNameText = uicontrol(fig,'Style','text',...
    'String', ['subject ID: ' trial.log.subject],...
    'Position',[xPosition yPosition-textblock*verticalDistance width height],...
    'HorizontalAlignment','left'); %#ok<*NASGU>

textblock = textblock+1;
subjectTypeText = uicontrol(fig,'Style','text',...
    'String', ['group: ' choice],...
    'Position',[xPosition yPosition-textblock*verticalDistance width height],...
    'HorizontalAlignment','left');

textblock = textblock+1;
trialText = uicontrol(fig,'Style','text',...
    'String', ['Trial: ' num2str(trial.number)],...
    'Position',[xPosition yPosition-textblock*verticalDistance width height],...
    'HorizontalAlignment','left');

textblock = textblock+1;
directionText = uicontrol(fig,'Style','text',...
    'String', ['Number of blinks: ' num2str(trial.saccades.numBlinks)],...
    'Position',[xPosition yPosition-textblock*verticalDistance width height],...
    'HorizontalAlignment','left');

textblock = textblock+1;
latencyText = uicontrol(fig,'Style','text',...
    'String', ['Gain: ' 'NaN'],...
    'Position',[xPosition yPosition-textblock*verticalDistance width height],...
    'HorizontalAlignment','left');

end


